import Head from "next/head";
import { Inter } from "@next/font/google";
import { styled } from "../stitches.config";
import Card from "../components/elements/Card";
import Header from "../components/elements/Header";
import Background from "../components/elements/Background";
import useSWR from "swr";

//Write a fetcher function to wrap the native fetch function and return the result of a call to url in json format
const fetcher = (url) =>
  fetch(url)
    .then((res) => res.json())
    .then((res) => JSON.parse(res));

const inter = Inter({ subsets: ["latin"] });

const AllUsage = () => {
  //Set up SWR to run the fetcher function when calling api
  const { data, error } = useSWR("/api/user_1", fetcher);

  let value = "";
  let usage = "";
  let date = "";
  let cleanDate = "";

  //Handle the error state
  if (error) return <div>Failed to load</div>;
  //Handle the loading state
  if (!data) return <div>Loading...</div>;

  const dateString = "2020-05-14T04:00:00Z";

  const formatDate = (dateString) => {
    const options = { month: "short", day: "numeric" };
    return new Date(dateString).toLocaleDateString("pt-PT", options);
  };

  console.log(formatDate(dateString));

  const UseHisto = data.hist_use.map((use, index) => {
    value = use.duration;
    usage = use.type;
    date = use.date;
    const options = { month: "short", day: "numeric" };
    cleanDate = new Date(date).toLocaleDateString("pt-PT", options);

    console.log(use.id);
    console.log(value);
    console.log(usage);
    console.log(date);
    return (
      <>
        <Card type="stroke">
          <CardItem className="flex justify-between items-center">
            <UsageInfo key={index}>
              <h4>{value}€</h4>
              <p className="mt-1">{usage}</p>
            </UsageInfo>
            <p className="text-muted">{cleanDate}</p>
          </CardItem>
        </Card>
      </>
    );
  });

  return (
    <>
      <Head>
        <title>Savee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Background color="orange" size="small" />
      <Header page="Histórico uso" />
      <div className="relative pt-20 px-6 flex flex-col gap-3 pb-6">
        <Card>
          <ThisMonth>120 min</ThisMonth>
          <p className="mt-2">Hoje</p>
        </Card>

        <h3 className="mt-6">Histórico de uso</h3>

        {UseHisto}
      </div>
    </>
  );
};

const ThisMonth = styled("div", {
  color: "$black",
  fontSize: "$f0",
  fontWeight: "$bolder",
  lineHeight: "3rem",
  flex: "1",
});

const UsageInfo = styled("div", {
  p: {
    fontSize: "$small",
  },
});

const CardItem = styled("div", {
  p: {
    fontSize: "$small",
  },
});

export default AllUsage;
