import Head from "next/head";
import { Inter } from "@next/font/google";
import Image from "next/image";
import { styled } from "../stitches.config";
import Card from "../components/elements/Card";
import Form from "../components/elements/Form";
import Button from "../components/elements/Button";
import Header from "../components/elements/Header";
import Breadcrumb from "../components/elements/Breadcrumb";
import Background from "../components/elements/Background";
import TaskList from "../components/routines/TaskList";
import DaySelector from "../components/routines/DaySelector";
import TimePeriodSelector from "../components/routines/TimePeriodSelector";
import TimeSelector from "../components/routines/TimeSelector";
import Link from "next/link";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Routine() {
  // state to keep track of the current step
  const [step, setStep] = useState(0);

  // Grouping forms by section in a component
  const TaskFields = () => (
    <>
      <p className="black ml-6">Escolhe a tarefa para criares uma rotina:</p>
      <TaskList />
    </>
  );

  const DayFields = () => (
    <>
      <p className="black">Escolhe os dias da semana</p>
      <DaySelector />
    </>
  );

  const PeriodFields = () => (
    <>
      <p className="black">Escolhe a altura do dia</p>
      <TimePeriodSelector />
    </>
  );

  const TimeFields = () => <TimeSelector />;

  // array of components to be rendered
  const fieldGroups = [
    <TaskFields key={""} />,
    <DayFields key={""} />,
    <PeriodFields key={""} />,
    <TimeFields key={""} />,
  ];

  // logic to navigate between steps
  const Navigation = () => (
    <>
      <div className="flex justify-center">
        {step === fieldGroups.length - 1 && (
          <>
            <Button
              className="mt-6 mr-4"
              bg="transparent"
              size="lg"
              onClick={() => {
                setStep(step - 1);
              }}
            >
              Anterior
            </Button>
            <Button className="mt-6" bg="solid" size="lg">
              Feito
            </Button>
          </>
        )}
        {step < fieldGroups.length - 1 &&
          step >= 0 && ( // mudar este condicional depois de termos os estados a funcionar
            <>
              {step < fieldGroups.length - 1 &&
                step > 0 && ( // tirar este condicional depois de termos os estados a funcionar
                  <Button
                    className="mt-6 mr-4"
                    bg="transparent"
                    size="lg"
                    onClick={() => {
                      if (step > 0) {
                        setStep(step - 1);
                      }
                    }}
                  >
                    Anterior
                  </Button>
                )}

              <Button
                className="mt-6"
                bg="solid"
                size="lg"
                onClick={() => {
                  setStep(step + 1);
                }}
              >
                Próximo
              </Button>
            </>
          )}
      </div>
    </>
  );

  return (
    <>
      <Head>
        <title>Savee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Background color="purple" />
      <Header page="Rotinas" />
      <div className="relative pt-20">
        <Breadcrumb />
        <Card>
          {fieldGroups[step]}
          <Navigation />
        </Card>
      </div>
    </>
  );
}
