import React from "react";
import Head from "next/head";
import Header from "../components/elements/Header";
import Background from "../components/elements/Background";
import Banner from "../components/elements/Banner";
import DashboardCard from "../components/elements/DashboardCard";
import Card from "../components/elements/Card";
import Tasks from "../components/dashboard/Tasks";
import RoutinesList from "../components/dashboard/RoutinesList";

export default function homepage() {
  const date = new Date().toLocaleDateString("pt-PT", {
    month: "long",
    day: "numeric",
  });

  return (
    <>
      <Head>
        <title>Savee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background color="mint" />
      <Header page="Homepage" />
      <div className="relative pt-20 px-6 flex flex-col gap-3">
        <h2>Olá Pedro!</h2>
        <Banner />
        <Card>
          <DashboardCard />
        </Card>

        <Tasks />
        <div>
          <div className="flex justify-between items-center">
            <h3>Hoje</h3>
            <p className="text-muted">{date}</p>
          </div>
        </div>
        <RoutinesList />
      </div>
    </>
  );
}
