import Head from "next/head";
import { Inter } from "@next/font/google";
import Button from "../components/elements/Button";
import Form from "../components/elements/Form";
import { styled } from "../stitches.config";
import Landing from "./Landing";

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Savee</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Landing/>
      </main>
    </>
  );
}
