import Head from "next/head";
import { Inter } from "@next/font/google";
import Image from "next/image";
import { styled } from "../stitches.config";
import Card from "../components/elements/Card";
import Form from "../components/elements/Form";
import Button from "../components/elements/Button";
import Background from "../components/elements/Background";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Register() {
  return (
    <>
      <Head>
        <title>Savee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background color="mint" />

      <div className="py-4 px-6">
        <Link href="/"><Image src="/img/logo.svg" alt="Logo" width={75} height={33} /></Link>
      </div>

      <div className="mx-6 mb-8">
        <h1 className="black">Criar conta</h1>
        <p className="black">Cria a tua conta no Savee e começa a poupar.</p>
      </div>

      <Card>
        <Form name="Email" />
        <div className="mt-6">
          <Form name="Password" />
        </div>
        <div className="flex justify-center">
          {/*todo: disable when form validation is set up*/}
          <Button className="mt-6" bg="solid" size="lg">
            Registar
          </Button>
        </div>
      </Card>
    </>
  );
}
