import React from "react";
import Head from "next/head";
import { styled } from "@stitches/react";
import Background from "../components/elements/Background";
import Card from "../components/elements/Card";
import Header from "../components/elements/Header";
import Task from "../components/elements/Task";
import Button from "../components/elements/Button";
import Timer from "../components/Timer";

export default function task() {
  return (
    <>
      <Head>
        <title>Savee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background color="yellow" />
      <Header page="Tarefa" />
      <div className="flex absolute top-20 flex-col">
        <div className="flex items-center gap-4 pl-6">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            className="w-6 h-6"
          >
            <path
              fillRule="evenodd"
              d="M11.03 3.97a.75.75 0 010 1.06l-6.22 6.22H21a.75.75 0 010 1.5H4.81l6.22 6.22a.75.75 0 11-1.06 1.06l-7.5-7.5a.75.75 0 010-1.06l7.5-7.5a.75.75 0 011.06 0z"
              clipRule="evenodd"
            />
          </svg>
          <h2>Homepage</h2>
        </div>
        <Card classes="flex flex-col justify-center items-center">
          <Task type="Secar cabelo" size="lg"></Task>
          <Timer />
          <Tip>
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              stroke-width="1.5"
              stroke="currentColor"
              className="w-6 h-6"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12V8.25z"
              />
            </svg>

            <p>
              Da última vez demoraste 5 min e 32 segundos. Se demorares menos 30
              segundos podes poupar o equivalente ao preço de um café.{" "}
            </p>
          </Tip>
        </Card>
      </div>
    </>
  );
}

const Tip = styled("div", {
  display: "flex",
  backgroundColor: "$skyblue",
  marginTop: "1.5rem",
  borderRadius: "0.25rem",
  padding: "0.5rem",
  gap: ".25rem",
  p: {
    fontSize: "$small",
  },
  svg: {
    flexShrink: 0,
  },
});
