import { React, useState } from "react";
import Head from "next/head";
import Background from "../components/elements/Background";
import Card from "../components/elements/Card";
import Header from "../components/elements/Header";
import Task from "../components/elements/Task";
import Timer from "../components/Timer";
import Breadcrumb from "../components/elements/Breadcrumb";

export default function task() {
  return (
    <>
      <Head>
        <title>Savee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background color="yellow" />
      <Header page="Tarefa" />
      <div className="relative pt-20 px-6 flex flex-col gap-3 pb-6">
        <Breadcrumb/>
        <Card classes="flex flex-col justify-center items-center">
          <Task size="lg"></Task>
          <Timer />
        </Card>
      </div>
    </>
  );
}
