import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../components/elements/Header";
import Card from "../components/elements/Card";
import Form from "../components/elements/Form";
import Tasks from "../components/dashboard/Tasks";
import DaySelector from "../components/routines/DaySelector";
import TimePeriodSelector from "../components/routines/TimePeriodSelector";
import TimeSelector from "../components/routines/TimeSelector";
import Insight from "../components/elements/Insight";
import TaskList from "../components/routines/TaskList";
import Summary from "../components/routines/Summary";
import DashboardCard from '../components/elements/DashboardCard';
import Banner from '../components/elements/Banner';
import RoutinesList from "../components/dashboard/TaskList";

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Savee</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header page="Homepage" />
      <div className="z-0 h-96 rounded-b-3xl bg-mint"></div>
      <RoutinesList/>

      <Card>
        <DashboardCard />
      </Card>
      <Card>
        <Form type='nome' />
        <Form type='date' />
      </Card>
      <Card type='stroke'>
        <Form type='nome' />
        <Form type='date' />
      </Card>
      <Tasks />
      <TaskList/>
      <DaySelector />
      <TimePeriodSelector />
      <TimeSelector/>
      <Summary/>
      <Insight />
    </>
  );
}
