import Head from "next/head";
import { Inter } from "@next/font/google";
import Header from "../components/elements/Header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Savee</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header page="Homepage" />
      <div className="z-0 h-96 rounded-b-3xl bg-mint"></div>
    </>
  );
}
