name: Periodic POST Request

on:
  schedule:
    - cron: "0 6,12,18 * * *"
  workflow_dispatch:

jobs:
  post_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Generate JWT token
        id: jwt
        env:
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
        run: |
          npm install jsonwebtoken
          echo "::set-output name=jwt_token::$(node -e "const jwt = require('jsonwebtoken'); const token = jwt.sign({}, process.env.TOKEN_SECRET); console.log(token);")"

      - name: Make POST request
        run: |
         echo "Authorization: Bearer ${{ steps.jwt.outputs.jwt_token }}"
         curl -X POST -H "Authorization: Bearer ${{ steps.jwt.outputs.jwt_token }}" https://savee-api.vercel.app/consumption/user/all
